FROM openresty/openresty:xenial
MAINTAINER Ye Jinshou <329365307@qq.com>

ADD nginx /usr/local/openresty/nginx/
ADD html /usr/local/openresty/nginx/html/

# -v /tmp/test/certs:/usr/local/openresty/nginx/conf/certs
